//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDDemo
{
    using System;
    
    public partial class mstEmployee
    {
        public int Id { get; set; }
        public string NIK { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAddress { get; set; }
        public string MarriedStatus { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
    }
    public enum MarriedStatusList
    {
        Married,
        Single
    }
}
